options:
  docker: true
pipelines:
  tags:
    '*':
    - step:
        name: Build and push Docker image on new git tag
        image: atlassian/default-image:4
        script:
          - export DOCKER_HUB_REPO=jwong235/bing-rewards
          - export IMAGE_TAG=$DOCKER_HUB_REPO:$BITBUCKET_TAG
          - export IMAGE_TAG_LATEST=$DOCKER_HUB_REPO:latest
           
          - docker login -u jwong235 -p $DOCKER_PASSWORD
          - docker buildx create --name mybuilder --use --driver docker-container
          - docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t $IMAGE_TAG -t $IMAGE_TAG_LATEST --load .
          - docker push $IMAGE_TAG
   
          - >
            if [[ ${BITBUCKET_TAG} =~ ^v[0-9]+\.[0-9]+(\.[0-9]+)?$ ]]; then
              docker push $IMAGE_TAG_LATEST
            fi
  pull-requests:
    '**':
    - step:
        image: python:3.9.13-slim
        caches:
          - pip
        script:
          - pip install flake8 black
          - apt-get update && apt-get install -y git
          - git fetch origin "+refs/heads/$BITBUCKET_PR_DESTINATION_BRANCH:refs/remotes/origin/$BITBUCKET_PR_DESTINATION_BRANCH"
          - export python_file_diff=$(git diff --name-only origin/$BITBUCKET_PR_DESTINATION_BRANCH... | grep '\.py$')
          - echo -e "Changed python files:\n$(echo $python_file_diff | tr ' ' '\n')"
          - if [ -n "$python_file_diff" ]; then echo $python_file_diff | xargs flake8 --config=.flake8; fi
          - if [ -n "$python_file_diff" ]; then echo $python_file_diff | xargs black --check; fi
    - step:
        image: jwong235/bing-rewards:latest
        script:
          - apt-get update && apt-get install -y jq
          - cd ..
          - python build/BingRewards/setup.py -e $MS_TEST_ACCOUNT -p $MS_TEST_PASSWORD
          - python build/BingRewards/BingRewards.py -nsb -m
          - log_output=$(jq -r --arg MS_TEST_ACCOUNT "$MS_TEST_ACCOUNT" '.[$MS_TEST_ACCOUNT] | .[-1]' build/BingRewards/logs/run.json)
          - echo "$log_output"
          # Test if program can be started, i.e log was written
          # It's not possible to test this futher because we can't enter the confirmation code
          - if [[ "$log_output" == *"Failed Edge Search"* ]]; then exit 0; else exit 1; fi


