options:
  docker: true
pipelines:
  tags:
    '*':
    - step:
        name: Build and push Docker image on new git tag
        image: atlassian/default-image:4
        script:
          - export DOCKER_HUB_REPO=jwong235/bing-rewards
          - export IMAGE_TAG=$DOCKER_HUB_REPO:$BITBUCKET_TAG
          - export IMAGE_TAG_LATEST=$DOCKER_HUB_REPO:latest
           
          - docker login -u jwong235 -p $DOCKER_PASSWORD
          - docker build -t $IMAGE_TAG -t $IMAGE_TAG_LATEST .
          - docker push $IMAGE_TAG
   
          - >
            if [[ ${BITBUCKET_TAG} =~ ^v[0-9]+\.[0-9]+(\.[0-9]+)?$ ]]; then
              docker push $IMAGE_TAG_LATEST
            fi
  pull-requests:
    '**':
    - step:
        image: python:3.9.13-slim
        caches:
          - pip
        script:
          - pip install flake8 black
          - apt-get update && apt-get install -y git
          - git fetch origin "+refs/heads/$BITBUCKET_PR_DESTINATION_BRANCH:refs/remotes/origin/$BITBUCKET_PR_DESTINATION_BRANCH"
          - export python_file_diff=$(git diff --name-only origin/$BITBUCKET_PR_DESTINATION_BRANCH... | grep '\.py$')
          - echo "Changed files:"
          - echo $python_file_diff | tr ' ' '\n'
          - echo $python_file_diff | xargs flake8 --config=.flake8
          - echo $python_file_diff | xargs black --check
